-- =========================================================
-- Supabase / PostgreSQL Database Schema for ShoeHub
-- Converted from MySQL (shoe_world (5).sql)
-- =========================================================

-- 1. DROP EXISTING TABLES (IF EXISTS)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREATE TABLES

-- Contact Messages Table
CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    zip VARCHAR(10) NOT NULL,
    card_name VARCHAR(100) NOT NULL,
    card_number VARCHAR(20) NOT NULL,
    expiry VARCHAR(7) NOT NULL,
    cvv VARCHAR(4) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    shipping NUMERIC(10,2) NOT NULL DEFAULT 5.00,
    total NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Order Items Table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL
);

-- Products Table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    material VARCHAR(100) NOT NULL,
    size_available VARCHAR(100) NOT NULL,
    color VARCHAR(50) NOT NULL,
    gender VARCHAR(20) CHECK (gender IN ('Men', 'Women', 'Unisex')) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    price NUMERIC(10,2) NOT NULL,
    ratings NUMERIC(2,1) NOT NULL DEFAULT 4.5,
    reviews INT NOT NULL DEFAULT 0,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS) FOR SUPABASE
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- 4. ROW LEVEL SECURITY POLICIES

-- Products: Everyone can read, insert, update
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public insert to products" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to products" ON products FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to products" ON products FOR DELETE USING (true);

-- Contact Messages: Everyone can submit and read
CREATE POLICY "Allow public insert to contact_messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access to contact_messages" ON contact_messages FOR SELECT USING (true);

-- Orders: Everyone can create and read orders
CREATE POLICY "Allow public insert to orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access to orders" ON orders FOR SELECT USING (true);

-- Order Items: Everyone can insert and read items
CREATE POLICY "Allow public insert to order_items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access to order_items" ON order_items FOR SELECT USING (true);

-- Users: Everyone can register and login
CREATE POLICY "Allow public insert to users" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read access to users" ON users FOR SELECT USING (true);


-- 5. SEED DATA INSERTION

-- Seed Products
INSERT INTO products (id, name, brand, description, material, size_available, color, gender, stock, price, ratings, reviews, image_url, created_at) VALUES
(1, 'Air Max 270', 'Nike', 'Stylish running shoes with air cushioning.', 'Mesh & Rubber', '7, 8, 9, 10, 11', 'Black & Red', 'Men', 50, 13995.00, 4.7, 180, 'images/Air Max 270 (Nike).avif', '2025-02-21 08:21:16+00'),
(2, 'Ultraboost 22', 'Adidas', 'Comfortable and high-performance running shoes.', 'Primeknit & Foam', '6, 7, 8, 9, 10', 'White & Blue', 'Unisex', 40, 17999.00, 4.8, 220, 'images/Ultraboost 22 (Adidas).jpg', '2025-02-21 08:21:16+00'),
(3, 'Wallabee', 'Clarks', 'Classic leather casual shoes.', 'Suede Leather', '7, 8, 9, 10', 'Brown', 'Men', 30, 12000.00, 4.6, 95, 'images/Wallabee (Clarks).png', '2025-02-21 08:21:16+00'),
(4, 'Chuck Taylor All Star', 'Converse', 'Iconic high-top sneakers.', 'Canvas & Rubber', '6, 7, 8, 9, 10', 'White', 'Unisex', 60, 5000.00, 4.5, 300, 'images/Chuck Taylor All Star (Converse).webp', '2025-02-21 08:21:16+00'),
(5, 'Stan Smith', 'Adidas', 'Minimalistic tennis shoes with great comfort.', 'Synthetic Leather', '5, 6, 7, 8, 9', 'Green & White', 'Unisex', 45, 8999.00, 4.7, 250, 'images/Stan Smith (Adidas).avif', '2025-02-21 08:21:16+00'),
(6, 'Air Force 1', 'Nike', 'Classic basketball shoes with a modern touch.', 'Leather', '7, 8, 9, 10, 11', 'Black', 'Men', 55, 11000.00, 4.8, 320, 'images/Air Force 1 (Nike).jpg', '2025-02-21 08:21:16+00'),
(7, 'Old Skool', 'Vans', 'Skateboarding sneakers with timeless design.', 'Suede & Canvas', '6, 7, 8, 9', 'Black & White', 'Unisex', 70, 6000.00, 4.6, 200, 'images/Old Skool (Vans).webp', '2025-02-21 08:21:16+00'),
(8, 'Gel-Kayano 28', 'ASICS', 'Stable and cushioned running shoes.', 'Mesh & Gel', '6, 7, 8, 9, 10', 'Blue & Yellow', 'Men', 35, 17000.00, 4.7, 140, 'images/Gel-Kayano 28 (ASICS).jpg', '2025-02-21 08:21:16+00'),
(9, 'Classic Clog', 'Crocs', 'Lightweight and comfortable clogs.', 'EVA Foam', '5, 6, 7, 8, 9', 'Navy Blue', 'Unisex', 80, 3000.00, 4.4, 500, 'images/Classic Clog (Crocs).jpg', '2025-02-21 08:21:16+00'),
(10, 'Puma RS-X', 'Puma', 'Chunky sneakers with retro styling.', 'Mesh & Suede', '7, 8, 9, 10', 'Red & White', 'Men', 45, 10000.00, 4.5, 130, 'images/Puma RS-X (Puma).webp', '2025-02-21 08:21:16+00'),
(11, 'Pegasus 39', 'Nike', 'Everyday running shoes with excellent responsiveness.', 'Flyknit & Foam', '6, 7, 8, 9, 10', 'Gray & Black', 'Unisex', 50, 13000.00, 4.6, 210, 'images/Pegasus 39 (Nike).avif', '2025-02-21 08:21:16+00'),
(12, 'Yeezy Boost 350 V2', 'Adidas', 'Trendy sneakers designed by Kanye West.', 'Primeknit & Boost', '7, 8, 9, 10', 'Zebra', 'Unisex', 20, 25000.00, 4.9, 400, 'images/Yeezy Boost 350 V2 (Adidas).avif', '2025-02-21 08:21:16+00'),
(13, 'Dr. Martens 1460', 'Dr. Martens', 'Iconic combat boots with great durability.', 'Leather', '6, 7, 8, 9, 10', 'Black', 'Unisex', 25, 18000.00, 4.8, 310, 'images/Dr. Martens 1460 (Dr. Martens).jpg', '2025-02-21 08:21:16+00'),
(14, 'Reebok Club C 85', 'Reebok', 'Classic tennis sneakers with a vintage feel.', 'Leather', '6, 7, 8, 9', 'White & Green', 'Unisex', 60, 7000.00, 4.5, 180, 'images/Reebok Club C 85 (Reebok).avif', '2025-02-21 08:21:16+00'),
(15, 'New Balance 574', 'New Balance', 'Stylish retro running shoes.', 'Suede & Mesh', '7, 8, 9, 10', 'Gray & White', 'Unisex', 55, 6500.00, 4.6, 230, 'images/New Balance 574 (New Balance).jpg', '2025-02-21 08:21:16+00');

-- Seed Contact Messages
INSERT INTO contact_messages (id, name, email, subject, message, created_at) VALUES
(10, 'Devam shah', 'devam6205@gmail.com', 'hello', 'HOW ARE YOU', '2025-02-23 12:15:10+00');

-- Seed Orders
INSERT INTO orders (id, first_name, last_name, email, address, city, state, zip, card_name, card_number, expiry, cvv, subtotal, shipping, total, created_at) VALUES
(11, 'Devam', 'Shah', 'devam6205@gmail.com', '101 Suvas Kanchan , Near Vakil House , Mahalaxmi Crossroad', 'Ahmedabad', 'Gujarat', '380007', 'Amazon ICICI', '010101010101', '20/05/2', '123', 641999.00, 5.00, 642004.00, '2025-02-23 11:58:07+00'),
(12, 'Hiral', 'Shah', 'hiraln123@gmail.com', '101 Suvas Kanchan , Near Vakil House , Mahalaxmi Crossroad', 'Ahmedabad', 'Gujarat', '380007', 'Amazon ICICI', '000000000', '20/05/2', '345', 35998.00, 5.00, 36003.00, '2025-02-23 12:13:37+00');

-- Seed Order Items
INSERT INTO order_items (id, order_id, product_name, quantity, price, subtotal) VALUES
(12, 11, 'Wallabee', 52, 12000.00, 624000.00),
(13, 11, 'Ultraboost 22', 1, 17999.00, 17999.00),
(14, 12, 'Ultraboost 22', 2, 17999.00, 35998.00);

-- Seed Users
INSERT INTO users (id, username, email, password_hash, created_at) VALUES
(1, 'john_doe', 'john@example.com', '$2y$10$TKh8H1.PORrs/DZ1EPtUIORvG2zfj12wLFGFtqEEdWZPOaA9lj/bW', '2025-01-06 16:25:50+00'),
(2, 'jane_smith', 'jane@example.com', '$2y$10$DxWRqQrz43cnJFPmfP0jXeXkRLJGyXZOVOFZxpQonvW6Nz1zHnhbS', '2025-01-06 16:25:50+00'),
(3, 'devam', 'devam6205@gmail.com', '$2y$10$r8ACxQRFAP82/zb470rjjuimIs5a.oGOjecxx69Ku8MOwIv6gGZPa', '2025-01-07 17:03:26+00');

-- 6. RESET IDENTITY SEQUENCES FOR FUTURE INSERTS
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1));
SELECT setval(pg_get_serial_sequence('contact_messages', 'id'), COALESCE((SELECT MAX(id) FROM contact_messages), 1));
SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1));
SELECT setval(pg_get_serial_sequence('order_items', 'id'), COALESCE((SELECT MAX(id) FROM order_items), 1));
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
